[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "446fdb8cd6028598b5165a7eabb35c5c8fbd4528"
libc = "glibc"
os = "linux"

    [[marble.download]]
    sha256 = "fbf8aa524919685020ea7157719bea96882d2e6a395ea24b03e73d48e6136c5c"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v23.3.90+0/marble.v23.3.90.x86_64-linux-gnu-cxx03.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45b486abcf19bd9151218fa46ac19a50bff3c63a"
libc = "glibc"
os = "linux"

    [[marble.download]]
    sha256 = "058f6ba3409af03203909cd95752cba8a388fd80668be3cf33d2f92f4ceef939"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v23.3.90+0/marble.v23.3.90.x86_64-linux-gnu-cxx11.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4b0898675757feb6d43f7430fb34995685748018"
os = "windows"

    [[marble.download]]
    sha256 = "301d1da857fae80c55e5cd0766bfb1c508e81e17a63560dc056612cc274af5e5"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v23.3.90+0/marble.v23.3.90.x86_64-w64-mingw32-cxx03.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "acfea22ebb23cd55e2bf97e280e09a9fb1c5e96c"
os = "windows"

    [[marble.download]]
    sha256 = "16fa4d4aa278e405936cc504a63e1b3a2c7957308fb186c1016ab48265982119"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v23.3.90+0/marble.v23.3.90.x86_64-w64-mingw32-cxx11.tar.gz"
