[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7c263bc517d8fc9a2854f605465d3957d6fa9233"
libc = "glibc"
os = "linux"

    [[marble.download]]
    sha256 = "4b72e4bd09c8449e3bdc19e5fde058316474dc2a08a00261bc9dcf0d98c9e5c1"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v20.12.0+1/marble.v20.12.0.x86_64-linux-gnu-cxx03.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5991f62e61fa51742fbb548c68c159f7fc8062"
libc = "glibc"
os = "linux"

    [[marble.download]]
    sha256 = "1171f2953bbf559eb42fa5863860ad93583e77f701a0c76c546d5d722fe72f41"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v20.12.0+1/marble.v20.12.0.x86_64-linux-gnu-cxx11.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a459b4bb092a214f1dec62bc8c768bc98190f600"
os = "windows"

    [[marble.download]]
    sha256 = "2944ed9bdc094e5dcb680fe67a92f30ab142c61818799fcb68fabfeb8c2d538c"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v20.12.0+1/marble.v20.12.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[marble]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a60dbe25ab1d7c743f5a1e95b9a35a0a717ebf4a"
os = "windows"

    [[marble.download]]
    sha256 = "c4fc8a346af686251170de32fa89659338830f5d0985065b49e7168f0aa33d01"
    url = "https://github.com/JuliaBinaryWrappers/marble_jll.jl/releases/download/marble-v20.12.0+1/marble.v20.12.0.x86_64-w64-mingw32-cxx11.tar.gz"
