# Autogenerated wrapper script for marble_jll for x86_64-linux-gnu-cxx11
export AnnotatePlugin, AprsPlugin, AtmospherePlugin, CachePlugin, CompassFloatItem, CrosshairsPlugin, CycleStreetsPlugin, EarthquakePlugin, EclipsesPlugin, ElevationProfileFloatItem, ElevationProfileMarker, FlightGearPositionProviderPlugin, FoursquarePlugin, GeoUriPlugin, GosmoreReverseGeocodingPlugin, GosmoreRoutingPlugin, GpsInfo, GpsbabelPlugin, GpxPlugin, GraticulePlugin, HostipPlugin, JsonPlugin, KmlPlugin, LatLonPlugin, License, LocalDatabasePlugin, LocalOsmSearchPlugin, LogPlugin, MapQuestPlugin, MapScaleFloatItem, MeasureTool, MonavPlugin, NavigationFloatItem, NominatimReverseGeocodingPlugin, NominatimSearchPlugin, NotesPlugin, OSRMPlugin, OpenLocationCodeSearchPlugin, OpenRouteServicePlugin, OsmPlugin, OverviewMap, Pn2Plugin, PntPlugin, PositionMarker, PostalCode, ProgressFloatItem, RoutingPlugin, RoutinoPlugin, SatellitesPlugin, Speedometer, StarsPlugin, SunPlugin, YoursPlugin, astro, marble_qt, marbledeclarative, marblewidget

using Qt_jll
using Libglvnd_jll
JLLWrappers.@generate_wrapper_header("marble")
JLLWrappers.@declare_library_product(AnnotatePlugin, "libAnnotatePlugin.so")
JLLWrappers.@declare_library_product(AprsPlugin, "libAprsPlugin.so")
JLLWrappers.@declare_library_product(AtmospherePlugin, "libAtmospherePlugin.so")
JLLWrappers.@declare_library_product(CachePlugin, "libCachePlugin.so")
JLLWrappers.@declare_library_product(CompassFloatItem, "libCompassFloatItem.so")
JLLWrappers.@declare_library_product(CrosshairsPlugin, "libCrosshairsPlugin.so")
JLLWrappers.@declare_library_product(CycleStreetsPlugin, "libCycleStreetsPlugin.so")
JLLWrappers.@declare_library_product(EarthquakePlugin, "libEarthquakePlugin.so")
JLLWrappers.@declare_library_product(EclipsesPlugin, "libEclipsesPlugin.so")
JLLWrappers.@declare_library_product(ElevationProfileFloatItem, "libElevationProfileFloatItem.so")
JLLWrappers.@declare_library_product(ElevationProfileMarker, "libElevationProfileMarker.so")
JLLWrappers.@declare_library_product(FlightGearPositionProviderPlugin, "libFlightGearPositionProviderPlugin.so")
JLLWrappers.@declare_library_product(FoursquarePlugin, "libFoursquarePlugin.so")
JLLWrappers.@declare_library_product(GeoUriPlugin, "libGeoUriPlugin.so")
JLLWrappers.@declare_library_product(GosmoreReverseGeocodingPlugin, "libGosmoreReverseGeocodingPlugin.so")
JLLWrappers.@declare_library_product(GosmoreRoutingPlugin, "libGosmoreRoutingPlugin.so")
JLLWrappers.@declare_library_product(GpsInfo, "libGpsInfo.so")
JLLWrappers.@declare_library_product(GpsbabelPlugin, "libGpsbabelPlugin.so")
JLLWrappers.@declare_library_product(GpxPlugin, "libGpxPlugin.so")
JLLWrappers.@declare_library_product(GraticulePlugin, "libGraticulePlugin.so")
JLLWrappers.@declare_library_product(HostipPlugin, "libHostipPlugin.so")
JLLWrappers.@declare_library_product(JsonPlugin, "libJsonPlugin.so")
JLLWrappers.@declare_library_product(KmlPlugin, "libKmlPlugin.so")
JLLWrappers.@declare_library_product(LatLonPlugin, "libLatLonPlugin.so")
JLLWrappers.@declare_library_product(License, "libLicense.so")
JLLWrappers.@declare_library_product(LocalDatabasePlugin, "libLocalDatabasePlugin.so")
JLLWrappers.@declare_library_product(LocalOsmSearchPlugin, "libLocalOsmSearchPlugin.so")
JLLWrappers.@declare_library_product(LogPlugin, "libLogPlugin.so")
JLLWrappers.@declare_library_product(MapQuestPlugin, "libMapQuestPlugin.so")
JLLWrappers.@declare_library_product(MapScaleFloatItem, "libMapScaleFloatItem.so")
JLLWrappers.@declare_library_product(MeasureTool, "libMeasureTool.so")
JLLWrappers.@declare_library_product(MonavPlugin, "libMonavPlugin.so")
JLLWrappers.@declare_library_product(NavigationFloatItem, "libNavigationFloatItem.so")
JLLWrappers.@declare_library_product(NominatimReverseGeocodingPlugin, "libNominatimReverseGeocodingPlugin.so")
JLLWrappers.@declare_library_product(NominatimSearchPlugin, "libNominatimSearchPlugin.so")
JLLWrappers.@declare_library_product(NotesPlugin, "libNotesPlugin.so")
JLLWrappers.@declare_library_product(OSRMPlugin, "libOSRMPlugin.so")
JLLWrappers.@declare_library_product(OpenLocationCodeSearchPlugin, "libOpenLocationCodeSearchPlugin.so")
JLLWrappers.@declare_library_product(OpenRouteServicePlugin, "libOpenRouteServicePlugin.so")
JLLWrappers.@declare_library_product(OsmPlugin, "libOsmPlugin.so")
JLLWrappers.@declare_library_product(OverviewMap, "libOverviewMap.so")
JLLWrappers.@declare_library_product(Pn2Plugin, "libPn2Plugin.so")
JLLWrappers.@declare_library_product(PntPlugin, "libPntPlugin.so")
JLLWrappers.@declare_library_product(PositionMarker, "libPositionMarker.so")
JLLWrappers.@declare_library_product(PostalCode, "libPostalCode.so")
JLLWrappers.@declare_library_product(ProgressFloatItem, "libProgressFloatItem.so")
JLLWrappers.@declare_library_product(RoutingPlugin, "libRoutingPlugin.so")
JLLWrappers.@declare_library_product(RoutinoPlugin, "libRoutinoPlugin.so")
JLLWrappers.@declare_library_product(SatellitesPlugin, "libSatellitesPlugin.so")
JLLWrappers.@declare_library_product(Speedometer, "libSpeedometer.so")
JLLWrappers.@declare_library_product(StarsPlugin, "libStarsPlugin.so")
JLLWrappers.@declare_library_product(SunPlugin, "libSunPlugin.so")
JLLWrappers.@declare_library_product(YoursPlugin, "libYoursPlugin.so")
JLLWrappers.@declare_library_product(astro, "libastro.so.1")
JLLWrappers.@declare_executable_product(marble_qt)
JLLWrappers.@declare_library_product(marbledeclarative, "libmarbledeclarative.so")
JLLWrappers.@declare_library_product(marblewidget, "libmarblewidget-qt5.so.28")
function __init__()
    JLLWrappers.@generate_init_header(Qt_jll, Libglvnd_jll)
    JLLWrappers.@init_library_product(
        AnnotatePlugin,
        "plugins/libAnnotatePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        AprsPlugin,
        "plugins/libAprsPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        AtmospherePlugin,
        "plugins/libAtmospherePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CachePlugin,
        "plugins/libCachePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CompassFloatItem,
        "plugins/libCompassFloatItem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CrosshairsPlugin,
        "plugins/libCrosshairsPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CycleStreetsPlugin,
        "plugins/libCycleStreetsPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        EarthquakePlugin,
        "plugins/libEarthquakePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        EclipsesPlugin,
        "plugins/libEclipsesPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ElevationProfileFloatItem,
        "plugins/libElevationProfileFloatItem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ElevationProfileMarker,
        "plugins/libElevationProfileMarker.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FlightGearPositionProviderPlugin,
        "plugins/libFlightGearPositionProviderPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FoursquarePlugin,
        "plugins/libFoursquarePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GeoUriPlugin,
        "plugins/libGeoUriPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GosmoreReverseGeocodingPlugin,
        "plugins/libGosmoreReverseGeocodingPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GosmoreRoutingPlugin,
        "plugins/libGosmoreRoutingPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpsInfo,
        "plugins/libGpsInfo.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpsbabelPlugin,
        "plugins/libGpsbabelPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpxPlugin,
        "plugins/libGpxPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GraticulePlugin,
        "plugins/libGraticulePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        HostipPlugin,
        "plugins/libHostipPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        JsonPlugin,
        "plugins/libJsonPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        KmlPlugin,
        "plugins/libKmlPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LatLonPlugin,
        "plugins/libLatLonPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        License,
        "plugins/libLicense.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LocalDatabasePlugin,
        "plugins/libLocalDatabasePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LocalOsmSearchPlugin,
        "plugins/libLocalOsmSearchPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LogPlugin,
        "plugins/libLogPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MapQuestPlugin,
        "plugins/libMapQuestPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MapScaleFloatItem,
        "plugins/libMapScaleFloatItem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MeasureTool,
        "plugins/libMeasureTool.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MonavPlugin,
        "plugins/libMonavPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NavigationFloatItem,
        "plugins/libNavigationFloatItem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NominatimReverseGeocodingPlugin,
        "plugins/libNominatimReverseGeocodingPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NominatimSearchPlugin,
        "plugins/libNominatimSearchPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NotesPlugin,
        "plugins/libNotesPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OSRMPlugin,
        "plugins/libOSRMPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OpenLocationCodeSearchPlugin,
        "plugins/libOpenLocationCodeSearchPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OpenRouteServicePlugin,
        "plugins/libOpenRouteServicePlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OsmPlugin,
        "plugins/libOsmPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OverviewMap,
        "plugins/libOverviewMap.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        Pn2Plugin,
        "plugins/libPn2Plugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PntPlugin,
        "plugins/libPntPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PositionMarker,
        "plugins/libPositionMarker.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PostalCode,
        "plugins/libPostalCode.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ProgressFloatItem,
        "plugins/libProgressFloatItem.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        RoutingPlugin,
        "plugins/libRoutingPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        RoutinoPlugin,
        "plugins/libRoutinoPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        SatellitesPlugin,
        "plugins/libSatellitesPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        Speedometer,
        "plugins/libSpeedometer.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        StarsPlugin,
        "plugins/libStarsPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        SunPlugin,
        "plugins/libSunPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        YoursPlugin,
        "plugins/libYoursPlugin.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        astro,
        "lib/libastro.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        marble_qt,
        "bin/marble-qt",
    )

    JLLWrappers.@init_library_product(
        marbledeclarative,
        "lib/libmarbledeclarative.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        marblewidget,
        "lib/libmarblewidget-qt5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
