# Autogenerated wrapper script for marble_jll for x86_64-w64-mingw32-cxx03
export AnnotatePlugin, AprsPlugin, AtmospherePlugin, CachePlugin, CompassFloatItem, CrosshairsPlugin, CycleStreetsPlugin, EarthquakePlugin, EclipsesPlugin, ElevationProfileFloatItem, ElevationProfileMarker, FlightGearPositionProviderPlugin, FoursquarePlugin, GeoUriPlugin, GosmoreReverseGeocodingPlugin, GosmoreRoutingPlugin, GpsInfo, GpsbabelPlugin, GpxPlugin, GraticulePlugin, HostipPlugin, JsonPlugin, KmlPlugin, LatLonPlugin, License, LocalDatabasePlugin, LocalOsmSearchPlugin, LogPlugin, MapQuestPlugin, MapScaleFloatItem, MeasureTool, MonavPlugin, NavigationFloatItem, NominatimReverseGeocodingPlugin, NominatimSearchPlugin, NotesPlugin, OSRMPlugin, OpenLocationCodeSearchPlugin, OpenRouteServicePlugin, OsmPlugin, OverviewMap, Pn2Plugin, PntPlugin, PositionMarker, PostalCode, ProgressFloatItem, RoutingPlugin, RoutinoPlugin, SatellitesPlugin, Speedometer, StarsPlugin, SunPlugin, YoursPlugin, astro, marble_qt, marbledeclarative, marblewidget

using Qt_jll
using Libglvnd_jll
JLLWrappers.@generate_wrapper_header("marble")
JLLWrappers.@declare_library_product(AnnotatePlugin, "libAnnotatePlugin.dll")
JLLWrappers.@declare_library_product(AprsPlugin, "libAprsPlugin.dll")
JLLWrappers.@declare_library_product(AtmospherePlugin, "libAtmospherePlugin.dll")
JLLWrappers.@declare_library_product(CachePlugin, "libCachePlugin.dll")
JLLWrappers.@declare_library_product(CompassFloatItem, "libCompassFloatItem.dll")
JLLWrappers.@declare_library_product(CrosshairsPlugin, "libCrosshairsPlugin.dll")
JLLWrappers.@declare_library_product(CycleStreetsPlugin, "libCycleStreetsPlugin.dll")
JLLWrappers.@declare_library_product(EarthquakePlugin, "libEarthquakePlugin.dll")
JLLWrappers.@declare_library_product(EclipsesPlugin, "libEclipsesPlugin.dll")
JLLWrappers.@declare_library_product(ElevationProfileFloatItem, "libElevationProfileFloatItem.dll")
JLLWrappers.@declare_library_product(ElevationProfileMarker, "libElevationProfileMarker.dll")
JLLWrappers.@declare_library_product(FlightGearPositionProviderPlugin, "libFlightGearPositionProviderPlugin.dll")
JLLWrappers.@declare_library_product(FoursquarePlugin, "libFoursquarePlugin.dll")
JLLWrappers.@declare_library_product(GeoUriPlugin, "libGeoUriPlugin.dll")
JLLWrappers.@declare_library_product(GosmoreReverseGeocodingPlugin, "libGosmoreReverseGeocodingPlugin.dll")
JLLWrappers.@declare_library_product(GosmoreRoutingPlugin, "libGosmoreRoutingPlugin.dll")
JLLWrappers.@declare_library_product(GpsInfo, "libGpsInfo.dll")
JLLWrappers.@declare_library_product(GpsbabelPlugin, "libGpsbabelPlugin.dll")
JLLWrappers.@declare_library_product(GpxPlugin, "libGpxPlugin.dll")
JLLWrappers.@declare_library_product(GraticulePlugin, "libGraticulePlugin.dll")
JLLWrappers.@declare_library_product(HostipPlugin, "libHostipPlugin.dll")
JLLWrappers.@declare_library_product(JsonPlugin, "libJsonPlugin.dll")
JLLWrappers.@declare_library_product(KmlPlugin, "libKmlPlugin.dll")
JLLWrappers.@declare_library_product(LatLonPlugin, "libLatLonPlugin.dll")
JLLWrappers.@declare_library_product(License, "libLicense.dll")
JLLWrappers.@declare_library_product(LocalDatabasePlugin, "libLocalDatabasePlugin.dll")
JLLWrappers.@declare_library_product(LocalOsmSearchPlugin, "libLocalOsmSearchPlugin.dll")
JLLWrappers.@declare_library_product(LogPlugin, "libLogPlugin.dll")
JLLWrappers.@declare_library_product(MapQuestPlugin, "libMapQuestPlugin.dll")
JLLWrappers.@declare_library_product(MapScaleFloatItem, "libMapScaleFloatItem.dll")
JLLWrappers.@declare_library_product(MeasureTool, "libMeasureTool.dll")
JLLWrappers.@declare_library_product(MonavPlugin, "libMonavPlugin.dll")
JLLWrappers.@declare_library_product(NavigationFloatItem, "libNavigationFloatItem.dll")
JLLWrappers.@declare_library_product(NominatimReverseGeocodingPlugin, "libNominatimReverseGeocodingPlugin.dll")
JLLWrappers.@declare_library_product(NominatimSearchPlugin, "libNominatimSearchPlugin.dll")
JLLWrappers.@declare_library_product(NotesPlugin, "libNotesPlugin.dll")
JLLWrappers.@declare_library_product(OSRMPlugin, "libOSRMPlugin.dll")
JLLWrappers.@declare_library_product(OpenLocationCodeSearchPlugin, "libOpenLocationCodeSearchPlugin.dll")
JLLWrappers.@declare_library_product(OpenRouteServicePlugin, "libOpenRouteServicePlugin.dll")
JLLWrappers.@declare_library_product(OsmPlugin, "libOsmPlugin.dll")
JLLWrappers.@declare_library_product(OverviewMap, "libOverviewMap.dll")
JLLWrappers.@declare_library_product(Pn2Plugin, "libPn2Plugin.dll")
JLLWrappers.@declare_library_product(PntPlugin, "libPntPlugin.dll")
JLLWrappers.@declare_library_product(PositionMarker, "libPositionMarker.dll")
JLLWrappers.@declare_library_product(PostalCode, "libPostalCode.dll")
JLLWrappers.@declare_library_product(ProgressFloatItem, "libProgressFloatItem.dll")
JLLWrappers.@declare_library_product(RoutingPlugin, "libRoutingPlugin.dll")
JLLWrappers.@declare_library_product(RoutinoPlugin, "libRoutinoPlugin.dll")
JLLWrappers.@declare_library_product(SatellitesPlugin, "libSatellitesPlugin.dll")
JLLWrappers.@declare_library_product(Speedometer, "libSpeedometer.dll")
JLLWrappers.@declare_library_product(StarsPlugin, "libStarsPlugin.dll")
JLLWrappers.@declare_library_product(SunPlugin, "libSunPlugin.dll")
JLLWrappers.@declare_library_product(YoursPlugin, "libYoursPlugin.dll")
JLLWrappers.@declare_library_product(astro, "libastro.dll")
JLLWrappers.@declare_executable_product(marble_qt)
JLLWrappers.@declare_library_product(marbledeclarative, "libmarbledeclarative.dll")
JLLWrappers.@declare_library_product(marblewidget, "libmarblewidget-qt5.dll")
function __init__()
    JLLWrappers.@generate_init_header(Qt_jll, Libglvnd_jll)
    JLLWrappers.@init_library_product(
        AnnotatePlugin,
        "plugins\\libAnnotatePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        AprsPlugin,
        "plugins\\libAprsPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        AtmospherePlugin,
        "plugins\\libAtmospherePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CachePlugin,
        "plugins\\libCachePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CompassFloatItem,
        "plugins\\libCompassFloatItem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CrosshairsPlugin,
        "plugins\\libCrosshairsPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        CycleStreetsPlugin,
        "plugins\\libCycleStreetsPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        EarthquakePlugin,
        "plugins\\libEarthquakePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        EclipsesPlugin,
        "plugins\\libEclipsesPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ElevationProfileFloatItem,
        "plugins\\libElevationProfileFloatItem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ElevationProfileMarker,
        "plugins\\libElevationProfileMarker.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FlightGearPositionProviderPlugin,
        "plugins\\libFlightGearPositionProviderPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        FoursquarePlugin,
        "plugins\\libFoursquarePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GeoUriPlugin,
        "plugins\\libGeoUriPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GosmoreReverseGeocodingPlugin,
        "plugins\\libGosmoreReverseGeocodingPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GosmoreRoutingPlugin,
        "plugins\\libGosmoreRoutingPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpsInfo,
        "plugins\\libGpsInfo.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpsbabelPlugin,
        "plugins\\libGpsbabelPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GpxPlugin,
        "plugins\\libGpxPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        GraticulePlugin,
        "plugins\\libGraticulePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        HostipPlugin,
        "plugins\\libHostipPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        JsonPlugin,
        "plugins\\libJsonPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        KmlPlugin,
        "plugins\\libKmlPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LatLonPlugin,
        "plugins\\libLatLonPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        License,
        "plugins\\libLicense.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LocalDatabasePlugin,
        "plugins\\libLocalDatabasePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LocalOsmSearchPlugin,
        "plugins\\libLocalOsmSearchPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        LogPlugin,
        "plugins\\libLogPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MapQuestPlugin,
        "plugins\\libMapQuestPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MapScaleFloatItem,
        "plugins\\libMapScaleFloatItem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MeasureTool,
        "plugins\\libMeasureTool.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        MonavPlugin,
        "plugins\\libMonavPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NavigationFloatItem,
        "plugins\\libNavigationFloatItem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NominatimReverseGeocodingPlugin,
        "plugins\\libNominatimReverseGeocodingPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NominatimSearchPlugin,
        "plugins\\libNominatimSearchPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        NotesPlugin,
        "plugins\\libNotesPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OSRMPlugin,
        "plugins\\libOSRMPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OpenLocationCodeSearchPlugin,
        "plugins\\libOpenLocationCodeSearchPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OpenRouteServicePlugin,
        "plugins\\libOpenRouteServicePlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OsmPlugin,
        "plugins\\libOsmPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        OverviewMap,
        "plugins\\libOverviewMap.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        Pn2Plugin,
        "plugins\\libPn2Plugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PntPlugin,
        "plugins\\libPntPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PositionMarker,
        "plugins\\libPositionMarker.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        PostalCode,
        "plugins\\libPostalCode.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        ProgressFloatItem,
        "plugins\\libProgressFloatItem.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        RoutingPlugin,
        "plugins\\libRoutingPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        RoutinoPlugin,
        "plugins\\libRoutinoPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        SatellitesPlugin,
        "plugins\\libSatellitesPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        Speedometer,
        "plugins\\libSpeedometer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        StarsPlugin,
        "plugins\\libStarsPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        SunPlugin,
        "plugins\\libSunPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        YoursPlugin,
        "plugins\\libYoursPlugin.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        astro,
        "bin\\libastro.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        marble_qt,
        "bin\\marble-qt.exe",
    )

    JLLWrappers.@init_library_product(
        marbledeclarative,
        "bin\\libmarbledeclarative.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        marblewidget,
        "bin\\libmarblewidget-qt5.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
