# Autogenerated wrapper script for marble_jll for x86_64-linux-gnu-cxx11
export astro, marble_qt, marblewidget

using Qt_jll
using Libglvnd_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("marble")
JLLWrappers.@declare_library_product(astro, "libastro.so.1")
JLLWrappers.@declare_library_product(marblewidget, "libmarblewidget-qt5.so.28")
JLLWrappers.@declare_executable_product(marble_qt)
function __init__()
    JLLWrappers.@generate_init_header(Qt_jll, Libglvnd_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        astro,
        "lib/libastro.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        marblewidget,
        "lib/libmarblewidget-qt5.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        marble_qt,
        "bin/marble-qt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
